config/routes.rb
Rails.application.routes.draw do
  get 'recommendation/view'

  resources :categories

  get 'contact/view'

  get 'jobpool/search'

  get 'appllist/update_status'
  get 'appllist/list'

  get 'account/view'

  devise_for :employers, :controllers => { :registrations => "registrations" }
  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  devise_for :users
  resources :jobapplications

  get 'jobpool/index'
  post 'jobapplications/new'
  resources :jobs

  root to:'jobpool#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates_presence_of :name,:content,:field,:employer_name,:deadline,:tag
  has_many :jobapplications,dependent: :destroy
  belongs_to :employer
  has_one :category

  scope :by_search ,lambda{|search_text| where(Job.arel_table[:name].matches("%#{search_text}%").or Job.arel_table[:content].matches("%#{search_text}%").or Job.arel_table[:employer_name].matches("%#{search_text}%").or Job.arel_table[:field].matches("%#{search_text}%").or Job.arel_table[:tag].matches("%#{search_text}%") ) }

  def search_jobs(params)
    jobs=Job.by_search(params[:searchText])
    jobs = jobs.uniq
    return jobs
  end

  def applied_by(user)
    flag=TRUE
    self.jobapplications.each do |jobapplication|
        if jobapplication.user_id ==user.id
          flag=FALSE
          return flag
        end
    end
    flag
  end
  def outdated
    flag=FALSE
    if Time.now>self.deadline
      flag=TRUE
    end
    flag
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  # GET /jobs
  # GET /jobs.json
  def index
    @employer=current_employer
    @jobs = @employer.jobs
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @employer=current_employer
    @job = @employer.jobs.build(job_params)
    @job.employer_name=current_employer.employer_name
    # @job.employer_id=current_employer.employer_id
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :content, :field, :tag, :tag_id, :employer, :deadline, :employer_id)
    end
  before_action :authenticate_employer!

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>(the asteroid indicate the necessary blankets For this form)</p>
  <div class="field">
    <%="*" %><%= f.label :name %>    <br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%="*" %><%= f.label :content %><br>
    <%= f.text_area :content ,rows:8%>
  </div>
  <div class="field">
    <% category_array = Category.all.map { |category| [category.category_name] } %>
    <%="*" %><%= f.label :field %><br>
    <%= f.select :field,category_array,
                 :prompt=>'Select a Category' %>
  </div>
  <div class="field">
    <%="*" %><%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%="*" %><%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div style="color:white; "><h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/index.html.erb
<div style="color: white;"><h1>Jobs You have Posted</h1>

<table>

  <thead>
    <tr>
      <th><div style="color:white;font:bold 120% sans-serif;">Name</div></th>
      <th><div style="color:white;font:bold 120% sans-serif;">Content</div></th>
      <th><div style="color:white;font:bold 120% sans-serif;">Field</div></th>
      <th><div style="color:white;font:bold 120% sans-serif;">Tag</div></th>
      <th><div style="color:white;font:bold 120% sans-serif;">Employer</div></th>
      <th><div style="color:white;font:bold 120% sans-serif;">Deadline</div></th>
      <th><div style="color:white;font:bold 120% sans-serif;">Applications</div></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @jobs.each do |job| %>
      <tr class="<%= cycle('list_line_odd','list_line_odd') %>">
        <td><%= job.name %></td>
        <td><%= job.content %></td>
        <td><%= job.field %></td>
        <td><%= job.tag %></td>
        <td><%= job.employer_name %></td>
        <td><%= job.deadline %></td>
        <td><%= link_to 'View Applications', appllist_list_path(:job_id=>job) %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>

</table>

<br>

<div style="   font: bold 110% sans-serif;"><%= link_to 'New Job', new_job_path %></div>
</div>

app/views/jobs/new.html.erb
<div style="color:white; "><h1>New job</h1>

<%= render 'form' %>
<%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/show.html.erb
<div style="color:white; "><p id="notice"><%= notice %></p>

<div style="color:white; font: bold 150% sans-serif;"><p>
  <strong>Name:</strong>
  <%= @job.name %>
</p>


<p>
  <strong>Content:</strong>
  <%= @job.content %>
</p>

<p>
  <strong>Field:</strong>
  <%= @job.field %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @job.tag %>
</p>


<p>
  <strong>Employer:</strong>
  <%= @job.employer_name.to_s %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @job.deadline %>
</p>
</div>

<div style="color:white; font: bold 150% sans-serif;"><%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %></div>
    </div>