config/routes.rb
Rails.application.routes.draw do
  get 'recommendation/view'

  resources :categories

  get 'contact/view'

  get 'jobpool/search'

  get 'appllist/update_status'
  get 'appllist/list'

  get 'account/view'

  devise_for :employers, :controllers => { :registrations => "registrations" }
  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  devise_for :users
  resources :jobapplications

  get 'jobpool/index'
  post 'jobapplications/new'
  resources :jobs

  root to:'jobpool#index'

end

app/models/jobapplication.rb
class Jobapplication < ActiveRecord::Base
  validates_presence_of :name, :major
  validates_numericality_of :phone
  belongs_to :job
  belongs_to :user
end

app/controllers/jobapplications_controller.rb
class JobapplicationsController < ApplicationController
  before_action :set_jobapplication, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /jobapplications
  # GET /jobapplications.json
  def index
    @user=current_user
    @jobapplications = @user.jobapplications
  end

  # GET /jobapplications/1
  # GET /jobapplications/1.json
  def show
  end

  # GET /jobapplications/new
  def new
    @job=Job.find(params[:job_id])
    session[:job_id]=params[:job_id]
    @jobapplication = Jobapplication.new
  end

  # GET /jobapplications/1/edit
  def edit
  end

  # POST /jobapplications
  # POST /jobapplications.json
  def create
    @user=current_user
    @job=Job.find(session[:job_id])
    @jobapplication = @user.jobapplications.build(job:@job)
    @jobapplication.name=jobapplication_params[:name]
    @jobapplication.phone=jobapplication_params[:phone]
    @jobapplication.major=jobapplication_params[:major]
    @jobapplication.coverletter=jobapplication_params[:coverletter]
    @jobapplication.status="Pending"
    @jobapplication.job_name=@job.name
    @jobapplication.email=current_user.email
    @jobapplication.job_id=@job.id
    JobNotifier.received(@jobapplication).deliver
    respond_to do |format|
      if @jobapplication.save(jobapplication_params)
        format.html { redirect_to @jobapplication, notice: 'Jobapplication was successfully created.' }
        format.json { render :show, status: :created, location: @jobapplication }
      else
        format.html { render :new }
        format.json { render json: @jobapplication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobapplications/1
  # PATCH/PUT /jobapplications/1.json
  def update
    @user=current_user
    @job=Job.find(session[:job_id])
    @jobapplication.job_name=@job.name
    @jobapplication.email=current_user.email
    respond_to do |format|
      if @jobapplication.update(jobapplication_params)
        format.html { redirect_to @jobapplication, notice: 'Jobapplication was successfully updated.' }
        format.json { render :show, status: :ok, location: @jobapplication }
      else
        format.html { render :edit }
        format.json { render json: @jobapplication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobapplications/1
  # DELETE /jobapplications/1.json
  def destroy
    @jobapplication.destroy
    respond_to do |format|
      format.html { redirect_to jobapplications_url, notice: 'Jobapplication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jobapplication
      @jobapplication = Jobapplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jobapplication_params
      params.require(:jobapplication).permit(:name, :email, :job_name, :phone, :status, :user_id, :job_id, :coverletter, :major)
    end
end

app/helpers/jobapplications_helper.rb
module JobapplicationsHelper
end

app/views/jobapplications/_form.html.erb
<%= form_for(@jobapplication) do |f| %>
  <% if @jobapplication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jobapplication.errors.count, "error") %> prohibited this jobapplication from being saved:</h2>

      <ul>
      <% @jobapplication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>(the asteroid indicate the necessary blankets For this form)</p>
  <div class="field">
    <%= "*"%><%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= current_user.email %>
  </div>
  <div class="field">
    <%= "*"%><%= f.label :major %><br>
      <%= f.text_field :major %>
    </div>
  <div class="field">
    <%= "*"%><%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :coverletter %><br>
    <%= f.text_area :coverletter,rows:10 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobapplications/edit.html.erb
<div style="color:white; "><h1>Editing Job Application</h1>

<%= render 'form' %>
<%= link_to 'Show', @jobapplication %> |
<%= link_to 'Back', jobapplications_path %>
</div>

app/views/jobapplications/index.html.erb
<div style="color:white; "><h1>Jobs You have Applied</h1>

<table>
  <thead>
    <tr>
      <th>Job name</th>
      <th>Name</th>
      <th>Email</th>
      <th>Major</th>
      <th>Phone</th>
      <th>Coverletter</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobapplications.each do |jobapplication| %>
      <tr>
        <td><%= jobapplication.job_name %></td>
        <td><%= jobapplication.name %></td>
        <td><%= jobapplication.email %></td>
        <td><%= jobapplication.major %></td>
        <td><%= jobapplication.phone %></td>
        <td><%= jobapplication.coverletter %></td>
        <td><%= jobapplication.status %></td>
        <td><%= link_to 'View the Application',jobapplication%></td>
        <td><%= link_to 'Withdraw the Application', jobapplication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/jobapplications/new.html.erb
<div style="color:white; "><h1>New Job Application</h1>


  <%= "Applying Job Name: " + @job.name %><br>
  <%= "Employer: "+ @job.employer_name.to_s %>


<%= render 'form' %>

<%= link_to 'Back', jobpool_index_url %>
</div>

app/views/jobapplications/show.html.erb
<div style="color:white; "><p id="notice"><%= notice %></p>
<p>
    <h1>Job Application:</h1>
</p>
<p>
  <strong>Job name:</strong>
  <%= @jobapplication.job_name %>
</p>
<p>
  <strong>Name:</strong>
  <%= @jobapplication.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @jobapplication.email %>
</p>
<p>
  <strong>Major:</strong>
  <%= @jobapplication.major %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @jobapplication.phone %>
</p>

<p>
  <strong>Status:</strong>
  <%= @jobapplication.status %>
</p>

<p>
  <strong>Coverletter:</strong>
  <%= @jobapplication.coverletter %>
</p>

<%= link_to 'Back', jobapplications_path %>
</div>