config/routes.rb
Rails.application.routes.draw do
  get 'recommendation/view'

  resources :categories

  get 'contact/view'

  get 'jobpool/search'

  get 'appllist/update_status'
  get 'appllist/list'

  get 'account/view'

  devise_for :employers, :controllers => { :registrations => "registrations" }
  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  devise_for :users
  resources :jobapplications

  get 'jobpool/index'
  post 'jobapplications/new'
  resources :jobs

  root to:'jobpool#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
  validates_presence_of :category_name
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs,dependent: :destroy
  validates_presence_of :employer_name
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates_presence_of :name,:content,:field,:employer_name,:deadline,:tag
  has_many :jobapplications,dependent: :destroy
  belongs_to :employer
  has_one :category

  scope :by_search ,lambda{|search_text| where(Job.arel_table[:name].matches("%#{search_text}%").or Job.arel_table[:content].matches("%#{search_text}%").or Job.arel_table[:employer_name].matches("%#{search_text}%").or Job.arel_table[:field].matches("%#{search_text}%").or Job.arel_table[:tag].matches("%#{search_text}%") ) }

  def search_jobs(params)
    jobs=Job.by_search(params[:searchText])
    jobs = jobs.uniq
    return jobs
  end

  def applied_by(user)
    flag=TRUE
    self.jobapplications.each do |jobapplication|
        if jobapplication.user_id ==user.id
          flag=FALSE
          return flag
        end
    end
    flag
  end
  def outdated
    flag=FALSE
    if Time.now>self.deadline
      flag=TRUE
    end
    flag
  end
end

app/models/jobapplication.rb
class Jobapplication < ActiveRecord::Base
  validates_presence_of :name, :major
  validates_numericality_of :phone
  belongs_to :job
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :jobapplications,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def view
    @users=User.order(:email)
    @admins=Admin.order(:email)
    @employers=Employer.order(:email)
  end
end

app/controllers/appllist_controller.rb
class AppllistController < ApplicationController
  def list
    # session[:job_id]=params[:job_id]
    @job=Job.find(params[:job_id])

    # @job=Job.find(params[:job_id])
    @jobapplications=@job.jobapplications
    # @jobapplications=Jobapplication.find_by_job_id(params[:job_id])
    # @jobapplications=Jobapplication.order(:name)
  end
  def update_status
    @jobapplication=Jobapplication.find(params[:jobapplication_id])
    status=params[:update_status].to_s
    JobNotifier.stupdated(@jobapplication).deliver
    respond_to do |format|
      if @jobapplication.update(:status=>status)
        format.html { redirect_to appllist_list_url(:job_id=>@jobapplication.job_id), notice: 'Jobapplication was successfully updated.' }
        format.json { render :show, status: :ok, location: @jobapplication }
      else
        format.html { render :edit }
        format.json { render json: @jobapplication.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def view
    @users=User.order(:email)
    @admins=Admin.order(:email)
    @employers=Employer.order(:email)
  end
end

app/controllers/jobpool_controller.rb
class JobpoolController < ApplicationController
  def index
    @user=current_user
    @jobs=Job.order(:created_at)
  end
  def search
    @user=current_user
    @text=params[:searchText]
    @jobs = Job.search_jobs(params)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  # GET /jobs
  # GET /jobs.json
  def index
    @employer=current_employer
    @jobs = @employer.jobs
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @employer=current_employer
    @job = @employer.jobs.build(job_params)
    @job.employer_name=current_employer.employer_name
    # @job.employer_id=current_employer.employer_id
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :content, :field, :tag, :tag_id, :employer, :deadline, :employer_id)
    end
  before_action :authenticate_employer!

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appllist_helper.rb
module AppllistHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/jobapplications_helper.rb
module JobapplicationsHelper
end

app/helpers/jobpool_helper.rb
module JobpoolHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/recommendation_helper.rb
module RecommendationHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/job_notifier/received.html.erb
Dear <%=@job.employer_name %>:
<br>
<%= @greeting %>
<br>
<%= @jobapplication.name %>  has applied the job you posted on the DireWolf Website. Please go to the DireWolf website and check the Job Application.
The following is the cover letter of the application.
<br>
Cover Letter:
<br>
<%= @jobapplication.coverletter %>

Thank you.
<br>
<br>
Best Regards,
<br>
DireWolf

app/views/job_notifier/received.text.erb
Dear <%=@job.employer_name %>:
<br>
<%= @greeting %>
<br>
<%= @jobapplication.name %>  has applied the job you posted on the DireWolf Website. Please go to the DireWolf website and check the Job Application.
The following is the cover letter of the application.
<br>
Cover Letter:
<br>
<%= @jobapplication.coverletter %>

Thank you.
<br>
<br>
Best Regards,
<br>
DireWolf

app/views/job_notifier/stupdated.html.erb
Dear <%=@jobapplication.name %>:
<br>
<%= @greeting %>
<br>
Thank you for applying the <%= @jobapplication.job_name %> at <%= @job.employer_name %>!
<br>
You application status has been updated.
<br>
Please go to the DireWolf website and check the status of your application.
<br>
Good luck!
<br>
If further infomation needed, we will contact you.
<br>
Best Regards,
<br>
<%=@job.employer_name%> Recuiter

app/views/job_notifier/stupdated.text.erb
Dear <%=@jobapplication.name %>:
<br>
<%= @greeting %>
<br>
Thank you for applying the <%= @jobapplication.job_name %> at <%= @job.employer_name %>!
<br>
You application status has been updated.
<br>
Please go to the DireWolf website and check the status of your application.
<br>
Good luck!
<br>
If further infomation needed, we will contact you.
<br>
Best Regards,
<br>
<%=@job.employer_name%> Recuiter

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
  <title>DireWolfJobPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller_name %>'>

  <div id="banner">
    <%= @page_title || "Direwolf Job Portal" %>
    <p class="navbar-text pull-right">
    <div style="background: #225378 color: white"><div id="login">
      <div style="padding-right:40px; color: #000000">
        <% if not admin_signed_in? and not employer_signed_in? %>
            <% if user_signed_in?%>
                <font color=#ffe4c4>Logged in as: <strong><%= current_user.email %></strong></font>
                <%= link_to 'Delete Account', user_registration_path, data: { confirm: "Are you sure?" }, method: :delete %>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
                <%= link_to "Job Seeker Login", new_user_session_path, :class => 'navbar-link'  %> |
            <% end %>
        <% end %>

        <% if not admin_signed_in? and not user_signed_in? %>
            <% if employer_signed_in? %>
                <font color="#ffe4c4">Logged in as: <strong><%= current_employer.email %></strong>.</font>
                <%= link_to 'Delete Account', employer_registration_path, data: { confirm: "Are you sure?" }, method: :delete %>
                <%= link_to 'Edit profile', edit_employer_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_employer_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
                <%= link_to "Employer Login", new_employer_session_path, :class => 'navbar-link'  %> |
            <% end %>
        <% end %>

        <% if not employer_signed_in? and not user_signed_in? %>
            <% if admin_signed_in? %>
                <font color="#ffe4c4">Logged in as: <strong><%= current_admin.email %></strong>.</font>
                <% if current_admin.email!="admin@admin.com"  %>
                    <%= link_to 'Delete Account', admin_registration_path, data: { confirm: "Are you sure?" }, method: :delete %>
                    <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
                <% end %>
                <%= link_to "Create Employer", new_employer_registration_path, :class => 'navbar-link'  %>|
                <%= link_to "Create Admin", new_admin_registration_path, :class => 'navbar-link'  %>
                <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>|
            <% else %>
                <%= link_to "Admin Login", new_admin_session_path, :class => 'navbar-link'  %>
            <% end %>
        <% end %>
      </div>
    </div>
    </div>
  </div>
  <div id="columns">
    <div id="side">
      <ul>
        <li><a href="http://52.6.120.225:3000">Home</a></li>
        <% if employer_signed_in? %>
        <div style="padding-top:20px;"><li><a href="http://52.6.120.225:3000/jobs">Publish a Job/View Job Application</a></li></div>
        <% end %>
        <% if user_signed_in? %>
        <div style="padding-top:20px;"><li><a href="http://52.6.120.225:3000/jobapplications">Job You Have Applied</a></li></div>
        <div style="padding-top:20px;"><li><a href="http://52.6.120.225:3000/recommendation/view">Job Recommendations</a></li></div>
        <% end %>
        <% if admin_signed_in? %>
            <div style="padding-top:20px;"><li><a href="http://52.6.120.225:3000/account/view">Set up Account</a></li></div>
            <div style="padding-top:20px;"><li><a href="http://52.6.120.225:3000/categories">Add a Job Category</a></li></div>
        <% end %>
        <div style="padding-top:20px;"><li><a href="http://52.6.120.225:3000/contact/view">Contact Us and Login Info</a></li></div>
      </ul>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
  </body>
</html>